name: Get Posts

on:
  schedule:
   - cron: '0 23 * * *' # runs at 11pm everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install python 3.9
        
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: execute scraper and exporter # export_to_mongodb.py
      env:
        MONGO_DB_PASS: ${{ secrets.MONGO_DB_PASS }}
      run: export_to_mongodb.py
